### ISSUE TITLE
HTTP Status 404 – Not Found

### ISSUE THREAD

**Issue by ukrishne** [SchweizerischeBundesbahnen/ch.sbb.polarion.extension.excel-importer#26]
### Current Behavior

Dear Team,

Thanks for your efforts.

![image](https://github.com/user-attachments/assets/2f94a26b-dc99-471e-9611-3b44f396b1e2)
![image](https://github.com/user-attachments/assets/ab8c6388-15a2-4b91-b709-a4cdddd896e7)
![image](https://github.com/user-attachments/assets/7c83f3b8-40c0-48fc-8d7d-38ac85fce915)
import exel menu missing in the below screen
![image](https://github.com/user-attachments/assets/7a1094b8-8d1f-44fc-b853-192d98da9b33)

### Expected Behavior

page should disply

### Steps To Reproduce

Windows OS
  excel-importer-2.6.1
2404 poalrion version 
ch.sbb.polarion.extension.excel-importer-2.6.1.jar

### Environment - OS

windows

### Polarion version

2404

### Extension Version

2.6.1

**Comment by grigoriev** [comment]
@ukrishne,
I think you are not installed Apache POI bundle as [here](https://github.com/SchweizerischeBundesbahnen/ch.sbb.polarion.extension.excel-importer?tab=readme-ov-file#installation-to-polarion) described.

**Comment by ukrishne** [comment]
Thanks i have tried to create paockge of "ch.sbb.polarion.thirdparty.bundles-1.3.0" i get below errors. Please check and advise.
C:\Users\ABCD>cd "C:\Users\ABCD\Downloads\ch.sbb.polarion.thirdparty.bundles-1.3.0"

C:\Users\ABCD\Downloads\ch.sbb.polarion.thirdparty.bundles-1.3.0>mvn clean package
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] Custom third-party dependencies                                    [pom]
[INFO] Custom Apache POI OSGi bundle                                      [jar]
[INFO]
[INFO] -------------< ch.sbb.polarion.thirdparty.bundles:bundles >-------------
[INFO] Building Custom third-party dependencies 1.3.0                     [1/2]
[INFO]   from pom.xml
[INFO] --------------------------------[ pom ]---------------------------------
[INFO]
[INFO] --- clean:3.2.0:clean (default-clean) @ bundles ---
[INFO]
[INFO] ---------< ch.sbb.polarion.thirdparty.bundles:org.apache.poi >----------
[INFO] Building Custom Apache POI OSGi bundle 1.3.0                       [2/2]
[INFO]   from bundles\org.apache.poi\pom.xml
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- clean:3.2.0:clean (default-clean) @ org.apache.poi ---
[INFO] Deleting C:\Users\ABCD\Downloads\ch.sbb.polarion.thirdparty.bundles-1.3.0\bundles\org.apache.poi\target
[INFO]
[INFO] --- resources:3.3.1:resources (default-resources) @ org.apache.poi ---
[INFO] Copying 1 resource from src\main\resources to target\classes
[INFO]
[INFO] --- compiler:3.13.0:compile (default-compile) @ org.apache.poi ---
[INFO] Nothing to compile - all classes are up to date.
[INFO]
[INFO] --- dependency:3.7.1:build-classpath (build-bundle-classpath) @ org.apache.poi ---
[INFO] Dependencies classpath:
libs/poi-ooxml-5.3.0.jar,libs/poi-5.3.0.jar,libs/commons-codec-1.17.0.jar,libs/commons-math3-3.6.1.jar,libs/SparseBitSet-1.3.jar,libs/poi-ooxml-lite-5.3.0.jar,libs/xmlbeans-5.2.1.jar,libs/commons-compress-1.26.2.jar,libs/commons-lang3-3.14.0.jar,libs/commons-io-2.16.1.jar,libs/curvesapi-1.08.jar,libs/log4j-api-2.23.1.jar,libs/commons-collections4-4.4.jar,libs/export-package-generator-1.0.0.jar,libs/guava-33.2.1-jre.jar,libs/failureaccess-1.0.2.jar,libs/listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar,libs/jsr305-3.0.2.jar,libs/checker-qual-3.42.0.jar,libs/error_prone_annotations-2.26.1.jar,libs/j2objc-annotations-3.0.0.jar
[INFO]
[INFO] --- exec:3.3.0:exec (default) @ org.apache.poi ---
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: ch/sbb/export_package_generator/PackageFinder has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:757)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:365)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:621)
[ERROR] Command execution failed.
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
    at org.apache.commons.exec.DefaultExecutor.executeInternal (DefaultExecutor.java:355)
    at org.apache.commons.exec.DefaultExecutor.execute (DefaultExecutor.java:253)
    at org.codehaus.mojo.exec.ExecMojo.executeCommandLine (ExecMojo.java:884)
    at org.codehaus.mojo.exec.ExecMojo.executeCommandLine (ExecMojo.java:844)
    at org.codehaus.mojo.exec.ExecMojo.execute (ExecMojo.java:450)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:126)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:328)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:316)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:212)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:174)
    at org.apache.maven.lifecycle.internal.MojoExecutor.access$000 (MojoExecutor.java:75)
    at org.apache.maven.lifecycle.internal.MojoExecutor$1.run (MojoExecutor.java:162)
    at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute (DefaultMojosExecutionStrategy.java:39)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:159)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:105)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:73)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:53)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:118)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:261)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:173)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:101)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:903)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:280)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:203)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:77)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:568)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:255)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:201)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:361)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:314)
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Custom third-party dependencies 1.3.0:
[INFO]
[INFO] Custom third-party dependencies .................... SUCCESS [  0.297 s]
[INFO] Custom Apache POI OSGi bundle ...................... FAILURE [  4.083 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  4.529 s
[INFO] Finished at: 2024-08-06T09:18:56+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:3.3.0:exec (default) on project org.apache.poi: Command execution failed.: Process exited with an error: 1 (Exit value: 1) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :org.apache.poi

**Comment by grigoriev** [comment]
@ukrishne,
building of apache poi bundle not related to excel importer. Could you please post the but there or use already compiled [binaries of Apache POI bundle](https://github.com/SchweizerischeBundesbahnen/ch.sbb.polarion.thirdparty.bundles/packages/2194821)?
